#!/usr/bin/env fish

read -l -P "December day: " DAY_NUM

set -l YEAR 2023
set -l YEAR_DIR "$HOME/git/advent_of_code/$YEAR/data/"
if not test -d $YEAR_DIR
  # If directory does not exist - create it
  echo "Creating directory '$YEAR_DIR'..."
  mkdir $YEAR_DIR -p
end

set -l SESSION_COOKIE (cat $HOME/git/advent_of_code/session_cookie.txt)
echo "Downloading data into '$YEAR_DIR/day$DAY_NUM.txt'..."
curl -H "Cookie: $SESSION_COOKIE" https://adventofcode.com/$YEAR/day/$DAY_NUM/input --output "$YEAR_DIR/day$DAY_NUM.txt"
